const data = [
  {
    id: 1,
    name: "Mark Webber",
    message: "reacted to your recent post",
    link: "My first tournament today!",
    time: "1m",
    img: "./assets/images/avatar-mark-webber.webp",
    alt: "avatar-mark-webber",
  },
  {
    id: 2,
    name: "Angela Gray",
    message: "followed you",
    time: "5m",
    img: "./assets/images/avatar-angela-gray.webp",
    alt: "avatar-angela-gray",
  },
  {
    id: 3,
    name: "Jacob Thompson",
    message: "has joined your group",
    link: "Chess Club",
    time: "1 day",
    img: "./assets/images/avatar-jacob-thompson.webp",
    alt: "avatar-jacob-thompson",
  },
  {
    id: 4,
    name: "Rizky Hasanuddin",
    message: "sent you a private message",
    subMassage:
      "Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.",
    time: "5 days",
    img: "./assets/images/avatar-rizky-hasanuddin.webp",
    alt: "avatar-rizky-hasanuddin",
  },
  {
    id: 5,
    name: "Kimberly Smith",
    message: "commented on your picture",
    img: "./assets/images/image-chess.jpg",
    time: "1 week",
    img: "./assets/images/avatar-kimberly-smith.webp",
    alt: "avatar-kimberly-smith",
  },
  {
    id: 6,
    name: "Nathan Peterson",
    message: "reacted to your recent post",
    link: "5 end-game strategies to increase your win rate",
    time: "2 weeks",
    img: "./assets/images/avatar-nathan-peterson.webp",
    alt: "avatar-nathan-peterson",
  },
  {
    id: 7,
    name: "Anna Kim",
    message: "left the group",
    link: "Chess Club",
    time: "2 weeks",
    img: "./assets/images/avatar-anna-kim.webp",
    alt: "avatar-anna-kim",
  },
];
